In [1]:
import numpy as np

from sklearn.linear_model import LinearRegression,Ridge,RidgeCV,Lasso
from sklearn.preprocessing import PolynomialFeatures,StandardScaler
from sklearn.datasets import make_regression


13.1 : Fitting a Line

In [2]:
features,target = make_regression(n_samples=100,
                                  n_features=3,
                                  n_informative=2,
                                  n_targets=1,
                                  noise=0.2,
                                  coef=False,
                                  random_state=1)

regression = LinearRegression()
model = regression.fit(features,target)

Discussion

In [3]:
model.intercept_

np.float64(-0.009650118178816669)

In [4]:
model.coef_

array([1.95531234e-02, 4.42087450e+01, 5.81494563e+01])

In [5]:
target[0]

np.float64(-20.870747595269407)

In [6]:
model.predict(features)[0]

np.float64(-20.861927709296808)

In [7]:
print(model.score(features,target))

0.9999901732607787


13.2 : Handing interactive Effects

In [8]:
features,target = make_regression(n_samples=100,
                                  n_features=2,
                                  n_informative=2,
                                  n_targets=2,
                                  noise=0.2,
                                  coef=False,
                                  random_state=1)

interactive = PolynomialFeatures(degree=3,
                                 include_bias=False,
                                 interaction_only=True)
features_interaction = interactive.fit_transform(features)
regression = LinearRegression()
model = regression.fit(features_interaction,target)

Discussion

In [9]:
features[0]

array([-1.89636092,  2.19069973])

In [10]:
interactive_tern = np.multiply(features[:,0],features[:,1])
interactive_tern[0]

np.float64(-4.15435735980631)

In [11]:
features_interaction[0]

array([-1.89636092,  2.19069973, -4.15435736])

13.3 : Fitting a Nonlinear Relationship

In [12]:
features,target = make_regression(n_samples=100,
                                  n_features=3,
                                  n_informative=2,
                                  n_targets=1,
                                  noise=0.2,
                                  coef=False,
                                  random_state=1)

polynomial = PolynomialFeatures(degree=3,include_bias=False)
features_polynomial = polynomial.fit_transform(features)
regression = LinearRegression()
model = regression.fit(features_polynomial,target)

Discussion

In [13]:
features[0]

array([ 0.58591043,  0.78477065, -0.95542526])

In [14]:
features[0]**2

array([0.34329103, 0.61586497, 0.91283743])

In [15]:
features[0]**3

array([ 0.2011378 ,  0.48331276, -0.87214794])

In [16]:
features_polynomial[0]

array([ 0.58591043,  0.78477065, -0.95542526,  0.34329103,  0.45980531,
       -0.55979363,  0.61586497, -0.74978971,  0.91283743,  0.2011378 ,
        0.26940473, -0.32798893,  0.36084171, -0.43930961,  0.53484097,
        0.48331276, -0.58841296,  0.71636803, -0.87214794])

13.4 : Reducing Variance with Regularization

In [17]:
features,target = make_regression(n_samples=100,
                                  n_features=3,
                                  n_informative=2,
                                  n_targets=1,
                                  noise=0.2,
                                  coef=False,
                                  random_state=1)

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)
regression = Ridge(alpha=0.5)
model = regression.fit(features_standardized,target)

Discussion

In [18]:
regr_cv = RidgeCV(alphas=[0.1,1.0,10.0])
model_cv = regr_cv.fit(features_standardized,target)
model_cv.coef_

array([1.29223201e-02, 4.40972291e+01, 5.38979372e+01])

In [19]:
model_cv.alpha_

np.float64(0.1)

13.5 : Reducing Features with Lasso Regression

In [20]:
features,target = make_regression(n_samples=100,
                                  n_features=3,
                                  n_informative=2,
                                  n_targets=1,
                                  noise=0.2,
                                  coef=False,
                                  random_state=1)

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)
regression = Lasso(alpha=0.5)
model = regression.fit(features_standardized,target)

Discussion

In [21]:
model.coef_

array([-0.        , 43.58618393, 53.39523724])

In [22]:
regression_a10 = Lasso(alpha=10)
model_a10 = regression_a10.fit(features_standardized,target)
model_a10.coef_

array([-0.        , 32.92181899, 42.73086731])