In [1]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.calibration import CalibratedClassifierCV

18.1 : Training a Classifier for Continuous Features

In [2]:
iris = load_iris()
features = iris.data
target = iris.target

classifer = GaussianNB()

model = classifer.fit(features,target)

Discussion

In [3]:
new_observation = [[4,4,4,0.4]]

model.predict(new_observation)

array([1])

In [4]:
clf = GaussianNB(priors=[0.25,0.25,0.5])
model = classifer.fit(features,target)

18.2 : Training a Classifier for Discrete and Count Features

In [5]:
text_data = np.array(['I love Brazil. Brazil!',
                      'Brazil is best',
                      'Germany beats both'])

count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

features = bag_of_words.toarray()

target = np.array([0,0,1])

classifer = MultinomialNB(class_prior=[0.25,0.5])

model = classifer.fit(features,target)

Discuccion

In [6]:
new_observation = [[0,0,0,1,0,1,0]]

model.predict(new_observation)

array([0])

18.3 : Training a Naive Bayes Classifier for Binary Features

In [7]:
features = np.random.randint(2,size=(100,3))
target = np.random.randint(2,size=(100,1)).ravel()

classifer = BernoulliNB(class_prior=[0.25,0.5])

model = classifer.fit(features,target)

Discussion

In [8]:
model_uniform_prior = BernoulliNB(class_prior=None,fit_prior=False)

18.4 : Calibrating Predicted Probabilities

In [9]:
iris = load_iris()
features = iris.data
target = iris.target

classifer = GaussianNB()

classifer_sigmoid = CalibratedClassifierCV(classifer,cv=2,method="sigmoid")

classifer_sigmoid.fit(features,target)

new_observation = [[2.6,2.6,2.6,0.4]]

classifer_sigmoid.predict_proba(new_observation)


array([[0.31859971, 0.63663451, 0.04476578]])

Discussion

In [10]:
classifer.fit(features,target).predict_proba(new_observation)  

array([[2.31548432e-04, 9.99768128e-01, 3.23532277e-07]])