In [1]:
import torch
import numpy as np

20.1 : Creating a Tensor

In [2]:
tensor_row = torch.tensor([1,2,3])

tensor_column = torch.tensor(
    [
    [1],
    [2],
    [3]
    ]
)

In [4]:
tensor_row

tensor([1, 2, 3])

In [3]:
tensor_column

tensor([[1],
        [2],
        [3]])

20.2 : Creating a Tensor from NumPy

In [5]:
vector_row = np.array([1,2,3])

tensor_row = torch.from_numpy(vector_row)

In [7]:
vector_row

array([1, 2, 3])

In [6]:
tensor_row

tensor([1, 2, 3])

20.3 : Creatinga Sparse Tensor

In [8]:
tensor = torch.tensor(
    [
        [0,0],
        [0,1],
        [3,0]
    ]
)

sparse_tensor = tensor.to_sparse()

In [10]:
tensor

tensor([[0, 0],
        [0, 1],
        [3, 0]])

In [9]:
sparse_tensor

tensor(indices=tensor([[1, 2],
                       [1, 0]]),
       values=tensor([1, 3]),
       size=(3, 2), nnz=2, layout=torch.sparse_coo)

Discussion

In [11]:
print(type(tensor))
print(type(sparse_tensor))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


20.4 : Selecting Elements in a Tensor

In [12]:
vector = torch.tensor([1,2,3,4,5,6])

matrix = torch.tensor(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

vector[2]

tensor(3)

In [13]:
matrix[1,1]

tensor(5)

Discussion

In [14]:
vector[:]

tensor([1, 2, 3, 4, 5, 6])

In [15]:
vector[:3]

tensor([1, 2, 3])

In [16]:
vector[3:]

tensor([4, 5, 6])

In [17]:
vector[-1]

tensor(6)

In [18]:
matrix[:2,:]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
matrix[:,1:2]

tensor([[2],
        [5],
        [8]])

In [20]:
vector[::-1]

ValueError: step must be greater than zero

In [21]:
vector.flip(dims=(-1,))

tensor([6, 5, 4, 3, 2, 1])

20.5 : Describing a Tensor

In [22]:
tensor = torch.tensor([[1,2,3],[1,2,3]])

tensor.shape

torch.Size([2, 3])

In [23]:
tensor.dtype

torch.int64

In [24]:
tensor.layout

torch.strided

In [25]:
tensor.device

device(type='cpu')

20.6 : Applying Operations to Elements

In [26]:
tensor = torch.tensor([1,2,3])

tensor *100

tensor([100, 200, 300])

20.7 : Finding the Maximum and Minimum Values

In [27]:
torch.tensor([1,2,3])

tensor.max()

tensor(3)

In [28]:
tensor.min()

tensor(1)

Discussion

In [30]:
tensor = torch.tensor([[1,2,3],
                       [1,2,5]])

tensor.max()

tensor(5)

20.8 : Reshaping Tensors

In [31]:
tensor = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9],
                       [10,11,12]])

tensor.reshape(2,6)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

20.9 : Transposing a Tensor

In [32]:
tensor = torch.tensor([[[1,2,3]]])

tensor.mT

tensor([[[1],
         [2],
         [3]]])

Discussion

In [33]:
tensor.permute(*torch.arange(tensor.ndim-1,-1,-1))

tensor([[[1]],

        [[2]],

        [[3]]])

20.10 : Flattening a Tensor

In [34]:
tensor = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

tensor.flatten()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

20.11 : Calculating Dot Products

In [35]:
tensor_1 = torch.tensor([1,2,3])

tensor_2 = torch.tensor([4,5,6])

tensor_1.dot(tensor_2)

tensor(32)

20.12 : Multiplying Tensors

In [36]:
tensor_1 = torch.tensor([1,2,3])

tensor_2 = torch.tensor([4,5,6])

tensor_1 * tensor_2

tensor([ 4, 10, 18])

Discussion

In [38]:
tensor_1 + tensor_2

tensor([5, 7, 9])

In [39]:
tensor_1 - tensor_2

tensor([-3, -3, -3])

In [40]:
tensor_1 / tensor_2

tensor([0.2500, 0.4000, 0.5000])