In [1]:
import numpy as np
from scipy import sparse

1.1 : Create a Vector

In [2]:
vector_row = np.array([1, 2, 3])
vector_column = np.array([[1], 
                       [2], 
                       [3]])
print(f"Vector_Row : \n{vector_row} ")
print(f"Vector_Column : \n{vector_column} ")

Vector_Row : 
[1 2 3] 
Vector_Column : 
[[1]
 [2]
 [3]] 


1.2 : Creating a Matrix

In [3]:
matrix = np.array([[1, 2],
                   [4, 5],
                   [7, 8]])
print(f"Matrix : \n{matrix} ")

Matrix : 
[[1 2]
 [4 5]
 [7 8]] 


Discussion

In [4]:
matrix_object = np.asmatrix([[1,2],
                         [1,2],
                         [1,2]])
print(f"Matrix Object : \n{matrix_object} ")

Matrix Object : 
[[1 2]
 [1 2]
 [1 2]] 


1.3 : Creating a Sparse Matrix

Sparse Matrix แสดงเฉพาะตำแหน่งและค่าที่ไม่เป็นศูนย์

In [5]:
matrix = np.array([[0,0],
                   [0,1],
                   [3,0]])
matrix_sparse = sparse.csr_matrix(matrix)
print(f"Sparse Matrix : \n{matrix_sparse} ")

Sparse Matrix : 
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3 


In [6]:
matrix_large = np.array([[0,0,0,0,0,0,0,0,0,0],
                         [0,1,0,0,0,0,0,0,0,0],
                         [3,0,0,0,0,0,0,0,0,0]])
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(f"Sparse Matrix Large : \n{matrix_large_sparse} ")

Sparse Matrix Large : 
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3 


1.4 : Preallocating Numpy Arrays

In [7]:
vector = np.zeros(shape=5)
print(vector)

[0. 0. 0. 0. 0.]


In [8]:
matrix = np.full(shape=(3,3), fill_value=1)
print(matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


1.5 : Selecting Elements

In [11]:
vector = np.array([1,2,3,4,5,6])
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

เลือกตำแหน่งที่ 3 ใน vector

In [12]:
vector[2]

np.int64(3)

เลือก แถวที่ 2 และ คอลัมน์ที่ 2 

In [13]:
matrix[1,1]

np.int64(5)

แสดงค่าทั้งหมดใน vector

In [14]:
vector[:]

array([1, 2, 3, 4, 5, 6])

เลือกทุกค่าจนถึงค่าที่ต้องการรวมอยู่ด้วย

In [15]:
vector[:3]

array([1, 2, 3])

เลือกทุกค่าจนหลังจากค่าที่ต้องการ

In [16]:
vector[3:]

array([4, 5, 6])

เลือกค่าสุดท้าย

In [17]:
vector[-1]

np.int64(6)

สลับตำแหน่งใน vector

In [18]:
vector[::-1]

array([6, 5, 4, 3, 2, 1])

In [19]:
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
matrix[:,1:2]

array([[2],
       [5],
       [8]])

1.6 : Describing a Matrix

In [21]:
matrix = np.array([[1, 2, 3,4],
                   [5, 6, 7,8],
                   [9,10,11,12]])

จำนวน แถว และ คอลัมน์

In [22]:
matrix.shape

(3, 4)

จำนวนทั้งหมด

In [23]:
matrix.size

12

In [24]:
matrix.ndim

2

1.7 : Applying Functions over Each Element

In [25]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [26]:
np.max(matrix)

np.int64(9)

In [27]:
np.min(matrix)

np.int64(1)

Discussion

คอลัมน์ที่มีค่ามากที่สุด

In [28]:
np.max(matrix,axis=0)

array([7, 8, 9])

แถวที่มีค่ามากที่สุด

In [29]:
np.max(matrix,axis=1)

array([3, 6, 9])

1.9 : Calculating the Average,Variance,and Standard Deviation

In [30]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [31]:
np.mean(matrix)

np.float64(5.0)

In [33]:
np.var(matrix)

np.float64(6.666666666666667)

In [35]:
np.std(matrix)

np.float64(2.581988897471611)

Discussion

In [36]:
np.mean(matrix,axis=0)

array([4., 5., 6.])

1.10 : Reshaping Arrays

In [37]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10,11,12]])

In [38]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Discussion

In [39]:
matrix.size

12

In [41]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [42]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

1.11 : Transposing a Vector or Matrix

In [43]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [44]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Disscussion

In [45]:
np.array([1,2,3,4,5,6]).T

array([1, 2, 3, 4, 5, 6])

In [46]:
np.array([[1,2,3,4,5,6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

1.12 : Flattening a Matrix

In [47]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

แปลงให้อยู่ในรูป 1 มิติ

In [48]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Discussion

In [49]:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
matrix_a = np.array([[1,2],
                     [3,4]])

In [52]:
matrix_a

array([[1, 2],
       [3, 4]])

In [53]:
matrix_b = np.array([[5,6],
                     [7,8]])

In [54]:
matrix_b

array([[5, 6],
       [7, 8]])

In [55]:
matrix_list = [matrix_a, matrix_b]
matrix_list

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [57]:
np.ravel(matrix_list)

array([1, 2, 3, 4, 5, 6, 7, 8])

1.13 : Finding the Rank of a Matrix

In [58]:
matrix = np.array([[1, 1, 1],
                   [1,1,10],
                   [1,1,15]])

In [59]:
np.linalg.matrix_rank(matrix)

np.int64(2)

1.14 : Getting the Diagonal of a Matrix

In [60]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

เลือกค่าแนวทะแยง จาก ซ้ายไปขวา

In [61]:
matrix.diagonal()

array([1, 4, 9])

In [62]:
matrix_1 = np.array([[1,2,3],
                     [4,5,6],   
                     [7,8,9]])

In [63]:
matrix_1.diagonal()

array([1, 5, 9])

Discussion

In [64]:
matrix.diagonal(offset=1)

array([2, 6])

In [65]:
matrix.diagonal(offset=-1)

array([2, 8])

1.15 : Calculating the Trace of a Matrix

In [68]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

ผลรวมแนวทะแยงจากซ้ายไปขวา

In [69]:
matrix.trace()

np.int64(14)

Discussion

In [70]:
sum(matrix.diagonal())

np.int64(14)

1.16 : Calculating Dot Products

In [71]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

In [72]:
np.dot(vector_a, vector_b)

np.int64(32)

Discission

In [74]:
vector_a @ vector_b 

np.int64(32)

ที่มาของการคิด

In [75]:
vector_a[0] * vector_b[0] + vector_a[1] * vector_b[1] + vector_a[2] * vector_b[2]

np.int64(32)

1.17 : Adding and Subtracting Matrices

In [76]:
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],  
                     [1, 1, 2]])
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],  
                     [1, 3, 8]])

matrix_a + matrix_b

In [77]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

matrix_a - matrix_b

In [78]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

Discussion

In [79]:
matrix_a+ matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [80]:
matrix_a-matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

1.18 : Multiplying Matrices

In [81]:
matrix_a = np.array([[1, 1],
                     [1, 2]])
matrix_b = np.array([[1, 3],
                     [1, 2]])

In [82]:
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

Discussion

คูณ Matrix

In [83]:
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

คูณตามตำแหน่ง

In [84]:
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

1.19 Inverting a Matrix

In [85]:
matrix = np.array([[1,4],
                   [2,5]])

In [86]:
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

Disussion

In [92]:
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

1.20 : Generating Random Values

In [94]:
np.random.seed(0)
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

Discussion

In [95]:
np.random.randint(0,11,3)

array([3, 7, 9], dtype=int32)

In [96]:
np.random.normal(0.0,1.0,3)

array([-1.42232584,  1.52006949, -0.29139398])

In [98]:
np.random.logistic(0.0,1.0,3)

array([-0.98118713, -0.08939902,  1.46416405])

In [99]:
np.random.uniform(1.0,2.0,3)

array([1.47997717, 1.3927848 , 1.83607876])